### PR TITLE
Update start.xqy

### PR DESCRIPTION
**Pull request by RoopaMalavally**

### CODE REVIEW

**Comment by kcoleman-marklogic** [comment]
@RoopaMalavally If you wish us to consider this pull request, please indicate why you feel this change is necessary. It looks purely cosmetic to me.

**Comment by RoopaMalavally** [comment]
Hi Kim,

Thanks for checking with me.

Jane has assigned me a project as part of an initial interview process.
There are some changes to content that she has requested, and I am trying
to incorporate them into the files. I am running into an issue with
Document Bulk Load and, therefore, unable to upload these changes at this
time.

Regards,
Roopa














***********************************************
*Clouds came floating into my life, *
*No longer to carry rain or usher storm, *
*But to add color to my sunset sky.*


*Rabindranath Tagore, Stray Birds*

**Comment by RoopaMalavally** [comment]
Roopa:

You do not need to make changes to the project on Github as part of the exercise. You only need to make changes to your local copy.

Thanks,
--Jane

**Comment by kcoleman-marklogic** [comment]
I am aware of the exercise Jane uses, but that is orthogonal to a request to make a permanent change to this project on github, which is what a pull request does. You are free to make any changes you like to your fork.

**Comment by RoopaMalavally** [comment]
Hi Jane,

Thanks for clarifying.

Kim, please ignore the pull requests.

Regards,
Roopa














***********************************************
*Clouds came floating into my life, *
*No longer to carry rain or usher storm, *
*But to add color to my sunset sky.*


*Rabindranath Tagore, Stray Birds*

**Pull request closed without merging**
